### ISSUE TITLE
Uso do LaPS Benchmark para TTS usado VC (Voice Conversion)

### ISSUE THREAD

**Issue by Pallas1303** [falabrasil/speech-datasets#10]
Olá, eu tenho um projeto em desenvolvimento que consiste em colocar suporte ao português brasileiro ao mecanismo Text-To-Speech chamado Festival Speech Synthesis. Atualmente está disponível uma voz do gênero masculino do dataset [THLS - An open source dataset for Brazilian Portuguese speech processing](https://lfelipesv.github.io/2018-10-23-thls-dataset/). 

Eu tenho planos para adicionar mais vozes para meu projeto. Devido que tem "poucos" datasets em PT-BR e o que há disponível são "massivos" demais para o meu ambiente de desenvolvimento escolhi utilizar a técnica de VC disponível no Festival. 

O LaPS Benchmark é do formato ideal. Sendo 20 frases o ideal para o treinar o modelo de VC, que no caso do Festival é baseado em GMM. 

Experimento que fiz para testar o VC do Festival:

Usei essa falante: 
https://gitlab.com/fb-audio-corpora/lapsbm16k/-/blob/master/LapsBM-F013/LapsBM_0252.wav?ref_type=heads

O resultados estão em minha pasta do Google Drive:
https://drive.google.com/drive/folders/11uNyj3ZWRF505wTVz0fhDL2AdmRLfv_B

Gostei do resultado e pretendo usar em meu projeto. Também pode ser útil para a "expansão" do LaPS Benchmark (no caso um dataset separado).

Existe uma condição para usar o LaPS Benchmark 16k além de mencionar-los em meu projeto?

**Comment by cassiotbatista** [comment]
Oi,

> Gostei do resultado e pretendo usar em meu projeto. Também pode ser útil para a "expansão" do LaPS Benchmark (no caso um dataset separado).

Legal, parabens! :)

> Existe uma condição para usar o LaPS Benchmark 16k além de mencionar-los em meu projeto?

Se nao for para fins comerciais, acho que o necessario seria apenas citar provavelmente esse paper: https://journal-bcs.springeropen.com/articles/10.1007/s13173-010-0023-1 

No mais, chegaste a tentar baixar a LapsBM pelo DVC aqui pelo GitHub mesmo? Pergunto porque tentei aqui e recebi um erro, mas acho estranho ninguem ainda ter reclamado. Alem disso, a maioria dos links do GitLab sao legados e nao damos mais manutencao.

```bash
$ # depoi de clonar o repo com 'git clone'
$ pip install 'dvc[gdrive]' && dvc pull -r public datasets/lapsbm
```

**Comment by Pallas1303** [comment]
Infelizmente não posso usar DVC, em meu ambiente o python não está funcionando direito. Tendo vários problemas com compatibilidade entre os pacotes. 

Com isso, utilizei o gitlab.

**Comment by cassiotbatista** [comment]
Oi,

Ok, sem problemas! Se eu tiver respondido todas as duvidas, acho que podes fechar a issue. Senao, posso esclarecer mais outros pontos, caso haja algum.

**Comment by Pallas1303** [comment]
Sim, entendo. Só queria sabe de uma coisa antes de fechar o isse. O que é a Laps?

**Comment by cassiotbatista** [comment]
LaPS e' a sigla do Laboratorio de Processamento de Sinais da UFPA. Foi onde o FalaBrasil surgiu: https://www.laps.ufpa.br/
